import { Fragment } from "react";
import Head from "next/head";

import HeroSection from "../components/HeroSection";
import Services from "../components/Services/ServiceList";
import IconsGrid from "../components/IconsGrid";
import FeatruedItems from "../components/FeaturedItems/FeaturedList";
import CompanyMessage from "../components/companyMessage";
import CallToActionBar from "../components/callToActionBar";

export default function Home() {
  const services = [
    {
      id: 1,
      title: "Service 1",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, numquam.",
    },
    {
      id: 2,
      title: "Service 1",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, numquam.",
    },
    {
      id: 3,
      title: "Service 1",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, numquam.",
    },
  ];
  const featuredItems = [
    {
      id: 1,
      title: "Service 1",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, numquam.",
    },
    {
      id: 2,
      title: "Service 1",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, numquam.",
    },
    {
      id: 3,
      title: "Service 1",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, numquam.",
    },
  ];
  return (
    <Fragment>
      <Head>
        <title>Eutoura Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection />
        <Services services={services} />
        {/* <IconsGrid icons={services} /> */}
        <FeatruedItems featuredItems={featuredItems} />
        <CompanyMessage />
        <CallToActionBar />
      </main>
    </Fragment>
  );
}
